import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import ts from 'typescript';
const code = ts.transpileModule(fs.readFileSync(new URL('../lib/game.ts', import.meta.url), 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText;
const { NightGame, inSlash } = await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const context = new Proxy({}, {get(_,key){if(key==='createRadialGradient')return()=>({addColorStop(){}});return()=>{};},set(){return true;}});
class Canvas extends EventTarget {getContext(){return context;} focus(){} getBoundingClientRect(){return{x:0,y:0,left:0,top:0,width:1280,height:720};}}
globalThis.window = new EventTarget();window.matchMedia=()=>({matches:false});
globalThis.document = new EventTarget();document.createElement=()=>new Canvas();
globalThis.requestAnimationFrame = ()=>1;globalThis.cancelAnimationFrame=()=>{};
function setup(){const g=new NightGame(new Canvas(),()=>{});g.start();g.events=new Set([0,1,2,3,4,5,6,7]);g.toast='';g.enemies=[];g.player.x=800;g.player.y=3200;g.player.a=0;return g;}
function key(type,k){const e=new Event(type);Object.defineProperty(e,'key',{value:k});window.dispatchEvent(e);}

test('keyboard movement is normalized; pause and focus loss clear held inputs',()=>{const g=setup();key('keydown','w');key('keydown','d');const{x,y}=g.player;g.update(.02);assert.ok(Math.abs(Math.hypot(g.player.x-x,g.player.y-y)-4.5)<.001);g.togglePause();assert.equal(g.keys.size,0);assert.equal(g.mode,'paused');key('keydown','q');assert.equal(g.player.q,0);g.togglePause();key('keydown','w');window.dispatchEvent(new Event('blur'));assert.equal(g.mode,'paused');assert.equal(g.keys.size,0);g.destroy();});
test('melee only hits its arc, builds energy, and advances a three-hit combo',()=>{const g=setup();g.player.energy=0;const front=g.spawn('elite',855,3200),back=g.spawn('elite',745,3200);g.action('attack');assert.equal(front.hp,262);assert.equal(back.hp,280);assert.equal(g.player.energy,1);const hp=front.hp;g.action('attack');assert.equal(front.hp,hp);g.player.atk=0;front.x=855;g.action('attack');assert.equal(front.hp,240);g.player.atk=0;front.x=855;g.action('attack');assert.equal(front.hp,206);assert.equal(g.player.energy,3);assert.equal(g.player.combo,2);assert.equal(inSlash(0,0,0,-30,0,88,10),false);g.destroy();});
test('piercing sword wave damages a target once and cannot fire without energy',()=>{const g=setup();g.player.energy=1;const e=g.spawn('elite',850,3200);g.action('ranged');assert.equal(g.player.energy,0);g.update(.04);assert.equal(e.hp,250);g.update(.01);assert.equal(e.hp,250);g.player.atk=0;const count=g.shots.length;g.action('ranged');assert.equal(g.shots.length,count);g.destroy();});
test('shield guards front strikes, heavy combo breaks guard, and back strikes work',()=>{const g=setup();const e=g.spawn('shield',850,3200);e.aim=Math.PI;g.action('attack');assert.equal(e.hp,115);g.player.atk=0;g.player.combo=1;g.player.comboTimer=.5;e.x=850;g.action('attack');assert.equal(e.hp,81);g.player.atk=0;e.aim=0;e.x=850;g.action('attack');assert.equal(e.hp,63);g.destroy();});
test('dodge grants brief invulnerability, cooldown blocks spam, river crossing stays on bridge',()=>{const g=setup();g.player.inv=0;const before=g.player.x;g.action('dodge');assert.ok(Math.abs(g.player.x-before-126)<1e-6);g.hurt(20);assert.equal(g.player.hp,100);g.action('dodge');assert.ok(Math.abs(g.player.x-before-126)<1e-6);g.player.inv=0;g.hurt(20);assert.equal(g.player.hp,80);g.player.x=500;g.player.y=2190;g.movePlayer(0,120);assert.ok(g.player.y<=2220);g.player.x=800;g.movePlayer(0,120);assert.ok(g.player.y>2220);g.destroy();});
test('telegraphed melee does not damage a player standing behind the enemy',()=>{const g=setup();g.player.inv=0;const e=g.spawn('shield',845,3200);e.aim=0;g.enemyAttack(e);assert.equal(g.player.hp,100);e.aim=Math.PI;g.enemyAttack(e);assert.equal(g.player.hp,88);g.destroy();});
test('camp checkpoint restores powers and event progression, allowing boss to respawn after death',()=>{const g=setup();g.events.delete(7);g.player.x=790;g.player.y=1300;g.player.hp=30;g.action('interact');assert.equal(g.mode,'upgrade');assert.equal(g.player.hp,100);const choice=g.choices[0];g.chooseUpgrade(choice);assert.ok(g.powers.has(choice));assert.ok(g.save.upgrades.includes(choice));g.player.y=700;g.updateEvents();assert.ok(g.enemies.some(e=>e.kind==='boss'));g.player.inv=0;g.hurt(200);assert.equal(g.mode,'dead');g.retry();assert.equal(g.player.y,1300);assert.equal(g.mode,'playing');assert.ok(g.powers.has(choice));assert.ok(!g.events.has(7));g.player.y=700;g.updateEvents();assert.equal(g.enemies.filter(e=>e.kind==='boss').length,1);g.destroy();});
test('boss phases create hazards, final blow clears threats, and lamp interaction completes the level',()=>{const g=setup();g.player.x=800;g.player.y=750;const boss=g.spawn('boss',800,500);boss.hp=400;boss.attack=2;g.enemyAttack(boss);assert.equal(g.hazards.length,6);g.hit(boss,500,false,true);assert.ok(g.bossDefeated);assert.equal(g.hazards.length,0);g.player.y=250;g.action('interact');assert.equal(g.mode,'won');g.destroy();});
test('death retry retains a playable initial route without permanently consuming early events',()=>{const g=new NightGame(new Canvas(),()=>{});g.start();g.player.y=3500;g.updateEvents();assert.ok(g.events.has(0));g.player.inv=0;g.hurt(120);g.retry();assert.equal(g.player.y,3930);assert.equal(g.events.size,0);g.player.y=3500;g.updateEvents();assert.ok(g.enemies.length>=2);g.destroy();});
test('clustered Z and X acquire targets without mouse, held Z chains, R pauses',()=>{const g=setup();g.aimMode='mouse';g.player.a=Math.PI;const e=g.spawn('elite',855,3200);key('keydown','z');assert.equal(g.aimMode,'auto');assert.equal(g.player.a,0);assert.equal(e.hp,262);g.player.atk=0;e.x=855;g.update(.01);assert.equal(e.hp,240);key('keyup','z');g.player.atk=0;key('keydown','x');assert.ok(g.shots.length>0);assert.ok(g.shots[0].vx>0);key('keyup','x');key('keydown','r');assert.equal(g.mode,'paused');key('keyup','r');g.destroy();});
test('F starts and retries, Z/X/C choose upgrades, movement sets facing without a target',()=>{const g=new NightGame(new Canvas(),()=>{});key('keydown','f');assert.equal(g.mode,'playing');g.events=new Set([0,1,2,3,4,5,6,7]);g.enemies=[];g.player.x=800;g.player.y=3200;key('keydown','a');g.update(.016);assert.ok(Math.abs(g.player.a-Math.PI)<1e-6);key('keyup','a');g.offerUpgrade();const choice=g.choices[1];key('keydown','x');assert.ok(g.powers.has(choice));assert.equal(g.mode,'playing');g.player.inv=0;g.hurt(200);key('keydown','f');assert.equal(g.mode,'playing');assert.equal(g.player.hp,100);g.destroy();});
